[application]

[web]
pre_compress = false

[[web.proxy]]
backend = "http://192.168.42.1/api/"

[web.app]
title = "web"

[web.wasm_opt]
level = "z"

[web.resource]
style = []
script = []

[web.resource.dev]
style = []
script = []
